// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: TRGB_ESP32S3

#include "ui.h"

void microphoneSetting_func(lv_event_t * e)
{
	// Your code here
}

void noiseCancelling_func(lv_event_t * e)
{
	// Your code here
}
