// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: TRGB_ESP32S3

#include "../ui.h"

void ui_Navigation_Screen_screen_init(void)
{
    ui_Navigation_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Navigation_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Navigation_Screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Navigation_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Navigator = lv_img_create(ui_Navigation_Screen);
    lv_img_set_src(ui_Navigator, &ui_img_navigation_png);
    lv_obj_set_width(ui_Navigator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Navigator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Navigator, 5);
    lv_obj_set_y(ui_Navigator, 15);
    lv_obj_set_align(ui_Navigator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Navigator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Navigator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Navigator, 75);

    ui_ArcDesign = lv_arc_create(ui_Navigation_Screen);
    lv_obj_set_width(ui_ArcDesign, 460);
    lv_obj_set_height(ui_ArcDesign, 500);
    lv_obj_set_x(ui_ArcDesign, 0);
    lv_obj_set_y(ui_ArcDesign, 20);
    lv_obj_set_align(ui_ArcDesign, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcDesign, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ArcDesign, LV_SCROLLBAR_MODE_OFF);
    lv_arc_set_value(ui_ArcDesign, 200);
    lv_obj_set_style_arc_color(ui_ArcDesign, lv_color_hex(0x416DB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcDesign, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcDesign, lv_color_hex(0x416DB4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcDesign, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcDesign, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcDesign, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Navigator, ui_event_Navigator, LV_EVENT_ALL, NULL);

}
