// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: TRGB_ESP32S3

#include "../ui.h"


// IMAGE DATA: assets/navigation.png
lv_img_dsc_t ui_img_navigation_png = {
    .header.always_zero = 0,
    .header.w = 512,
    .header.h = 512,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_navigation_png_load()
{
    ui_img_navigation_png.data = UI_LOAD_IMAGE("S:assets/ui_img_navigation_png.bin", 19694, 786432);
    ui_img_navigation_png.data_size = 786432;
}
